### ISSUE TITLE
Validations inside child components are triggered when a form in the parent is submitted

### ISSUE THREAD

**Issue by eakenbor** [vuelidate/vuelidate#1152]
I imported a child component inside a parent. The child has its own form and validation rules different from that of the parent. However, when I try to submit the parent form, all the validations including those in the child component are triggered. This should not be the case. I expect the validations in the child to be triggered only when I click on the submit button inside the child component.

Here are my codes:

Parent.vue
````
<template>
<form>
...
<form/>
<Child/>
</template>
import { useVuelidate } from "@vuelidate/core";
import { required, email } from "@vuelidate/validators";
import Child from "./Child.vue"

export default {
  setup() {
    return { v$: useVuelidate()};
  },
components: {
    Child,
  },
data(){
return {}
},
validations(){
return {
}
},
methods:{
onSubmit(){
this.v$.$touch()
}
} }
````

Child.vue
````
<template>
<form>
...
<form/>
</template>
import { useVuelidate } from "@vuelidate/core";
import { required, email } from "@vuelidate/validators";

export default {
  setup() {
    return { v$: useVuelidate()};
  },
data(){
return {}
},
validations(){
return {
}
},
methods:{
onSubmit(){
this.v$.$touch()
}
} }
````

**Comment by dobromir-hristov** [comment]
Check the stopPropagation option as well as the scope. Those should fix it for you

**Comment by eakenbor** [comment]
@dobromir-hristov thanks. However, event.stopPropagation() as well as event.preventDefault() don't work. The child validations still appear in the $silentErrors. 
How do you mean scope? Is there any example I can follow?

I am using it in Vue 3. My code:
````
<form @submit.prevent="onSubmit">
...<form/>

...
onSubmit(event) {
      event.stopPropagation()
      // event.preventDefault()

      this.v$.$touch();
...
}
````

**Comment by dobromir-hristov** [comment]
https://vuelidate-next.netlify.app/api/configuration.html#stoppropagation

**Comment by eakenbor** [comment]
@dobromir-hristov thanks. It's working now.
