### ISSUE TITLE
$pending not switching to `false` in async rule on input with debounce

### ISSUE THREAD

**Issue by engenes** [vuelidate/vuelidate#1190]
I am writing an asynchronous rule with a delayed promise. And the promise resolves, but the $pending does not switch its state when I enter multiple characters in a row.

But if I write one character at a time, then the pending works fine

The problem is that when you enter the `$pendingCounter.value` in `createResults.js` continues to increase, but the promise is not resolved yet

    "@vuelidate/core": "2.0.2",
    "@vuelidate/validators": "2.0.2",
    "vue": "3.2.45"

**Reproduction**: https://codesandbox.io/s/jovial-water-9pmv39?file=/src/App.vue

```
let timer;

const debouncedValidation = (value) =>
  new Promise((resolve) => {
    clearTimeout(timer);

    timer = setTimeout(() => {
      resolve(value === '111');
    }, 1000);
  });

const myRule= helpers.withAsync(async (value) => {
  const res = await debouncedValidation(value);
  console.log(res);

  return res;
});

const rules = {
  model: {
    required,
    myRule,
  },
};

const v$ = useVuelidate(rules, { model });
```

**Comment by RoundRobin-fr** [comment]
It's not a bug in vuelidate but in your `debounce` code.

When you call it only once, then the returned promise is correctly resolved by the `setTimeout`.

But if you call it twice or more while the timer is running, then the subsequent calls clear the timer and only the latest  promise gets resolved.

You could fix it with:
```
const debounce = (callback, timeout) => {
    let timer;
    const resolvers = [];
    return async (...args) => {
        clearTimeout(timer);
        return new Promise((resolve) => {
            resolvers.push(resolve);
            timer = setTimeout(async () => {
                const result = await callback.apply(this, args);
                resolvers.map((resolver) => resolver(result));
            }, timeout);
        });
    };
};
```

**Comment by engenes** [comment]
> It's not a bug in vuelidate but in your `debounce` code.
> 
> When you call it only once, then the returned promise is correctly resolved by the `setTimeout`.
> 
> But if you call it twice or more while the timer is running, then the subsequent calls clear the timer and only the latest promise gets resolved.
> 
> You could fix it with:
> 
> ```
> const debounce = (callback, timeout) => {
>     let timer;
>     const resolvers = [];
>     return async (...args) => {
>         clearTimeout(timer);
>         return new Promise((resolve) => {
>             resolvers.push(resolve);
>             timer = setTimeout(async () => {
>                 const result = await callback.apply(this, args);
>                 resolvers.map((resolver) => resolver(result));
>             }, timeout);
>         });
>     };
> };
> ```

Good solution, thanks!
but I would like it to be built into vuelidate
in order not to make this setting in every project

**Comment by engenes** [comment]
> It's not a bug in vuelidate but in your `debounce` code.
> 
> When you call it only once, then the returned promise is correctly resolved by the `setTimeout`.
> 
> But if you call it twice or more while the timer is running, then the subsequent calls clear the timer and only the latest promise gets resolved.
> 
> You could fix it with:
> 
> ```
> const debounce = (callback, timeout) => {
>     let timer;
>     const resolvers = [];
>     return async (...args) => {
>         clearTimeout(timer);
>         return new Promise((resolve) => {
>             resolvers.push(resolve);
>             timer = setTimeout(async () => {
>                 const result = await callback.apply(this, args);
>                 resolvers.map((resolver) => resolver(result));
>             }, timeout);
>         });
>     };
> };
> ```

https://codesandbox.io/s/jovial-water-9pmv39?file=/src/App.vue

@RoundRobin-fr
It still doesn't work.
When entering, function calls are delayed, but after the time has expired, they are all called at once, such a solution will not reduce the load in any way
