### ISSUE TITLE
Conditional required validators are not validating

### ISSUE THREAD

**Issue by littlejon85** [vuelidate/vuelidate#866]
**Describe the bug**
Validators `requiredIf` and `requiredUnless` stopped working in `@vuelidate/validators: ^2.0.0-alpha.14`.

The latest `alpha.15` has the same issue.

**Reproduction URL**
`2.0.0-alpha.13` is working as expected https://codesandbox.io/s/bug-vuelidate-2-requiredifunless-alpha13working-v304y
`^2.0.0-alpha.14` is broken https://codesandbox.io/s/bug-vuelidate-2-requiredifunless-alpha14broken-m85bp

The only difference between the two sandboxes is the version of `@vuelidate/validators`.

**To Reproduce**
1. Go to code sandbox
2. See that `requiredIf(true)` and `requiredUnless(false)` has `$invalid: false` if text filed is clear in `2.0.0-alpha.14` and up

**Expected behavior**
`requiredIf(true)` and `requiredUnless(false)` should have`$invalid: true` if text filed is clear

**Comment by dobromir-hristov** [comment]
Try again with latest 2.0.0-alpha.19. That should be fixed now.

**Comment by littlejon85** [comment]
Updated vuelidate core and validators to latest but the problem persists.

https://codesandbox.io/s/bug-vuelidate-2-requiredifunless-latest-t0iin?file=/package.json:251-334

```json
"@vuelidate/core": "2.0.0-alpha.19",
"@vuelidate/validators": "2.0.0-alpha.16",
```

**Comment by dobromir-hristov** [comment]
It's looks like a problem with the options API. I will investigate tonight.

**Comment by dobromir-hristov** [comment]
https://github.com/vuelidate/vuelidate/releases/tag/%40vuelidate%2Fvalidators%402.0.0-alpha.17 should have fixed this now. Please try it.

**Comment by littlejon85** [comment]
Awesome. It works as expected now. Thank you.
